[program:fs-watcher]
command=/home/root/python-venv/opencapture/bin/watcher -c /var/www/html/opencapture/instance/config/watcher.ini start
autostart=true
autorestart=true
stderr_logfile=/var/log/watcher/error.log
stdout_logfile=/var/log/watcher/daemon.log
stopasgroup=true
killasgroup=true
