[program:OCWorker_edissyum]
command=/var/www/html/opencapture/custom/edissyum/bin/scripts/OCVerifier_worker.sh
process_name=%(program_name)s_%(process_num)02d
numprocs=3
user=edissyum
chmod=0777
chown=edissyum:www-data
socket_owner=edissyum
stopsignal=QUIT
stopasgroup=true
killasgroup=true
stopwaitsecs=10

stderr_logfile=/var/www/html/opencapture/custom/edissyum/data/log/Supervisor/OCVerifier-worker_%(process_num)02d.log
