global:
  scrape_interval: 5s

scrape_configs:

  ########################################################
  # 🔥 BACKEND OPENCAPTURE (TON CODE)
  ########################################################
  - job_name: 'opencapture_backend'
    static_configs:
      - targets: ['opencapture:8000']

  ########################################################
  # NODE EXPORTER (CPU / RAM)
  ########################################################
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  ########################################################
  # CADVISOR (DOCKER)
  ########################################################
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']