[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/var/run/supervisord.pid

# init unix http server, then supervisorctl can interactive with supervisord
[unix_http_server]
file=/var/run/supervisor.sock
chmod=0755

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

# spectify unix http server file path
[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[include]
files = /etc/supervisor/conf.d/*.conf

[program:apache2]
command=/usr/sbin/apache2ctl -D FOREGROUND
autostart=true
autorestart=false
stderr_logfile=/var/log/supervisor/apache2.err.log
stdout_logfile=/var/log/supervisor/apache2.out.log
startsecs=0

[program:postgresql]
command=/usr/lib/postgresql/15/bin/postgres -D /var/lib/postgresql/15/main -c config_file=/etc/postgresql/15/main/postgresql.conf
user=postgres
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/postgresql.err.log
stdout_logfile=/var/log/supervisor/postgresql.out.log
startsecs=0

[program:rabbitmq-server]
command=/usr/sbin/rabbitmq-server
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/rabbitmq-stderr.log
stdout_logfile=/var/log/supervisor/rabbitmq-stdout.log
user=rabbitmq
priority=10
environment=HOME="/var/lib/rabbitmq"