ErrorDocument 400 /src/assets/error_pages/400.html
ErrorDocument 401 /src/assets/error_pages/401.html
ErrorDocument 403 /src/assets/error_pages/403.html
ErrorDocument 404 /src/assets/error_pages/404.html
ErrorDocument 500 /src/assets/error_pages/500.html
ErrorDocument 501 /src/assets/error_pages/501.html
ErrorDocument 502 /src/assets/error_pages/502.html
ErrorDocument 503 /src/assets/error_pages/503.html
ErrorDocument 504 /src/assets/error_pages/504.html
<VirtualHost *:80>
    ServerName opencapture.visiocompte.localhost
    ServerAlias apache_container
    DocumentRoot /var/www/html/opencapture/
    #WSGIDaemonProcess opencapturehttp user=opencapture group=www-data home=/var/www/html/opencapture/ threads=5 processes=1 python-path=/home/root/python-venv/opencapture/lib/python3.9/site-packages
    #WSGIScriptAlias /backend_oc /var/www/html/opencapture//wsgi.py

    RewriteEngine On
    # Ne rediriger que si l'hôte est opencapture.localhost
    RewriteCond %{HTTP_HOST} ^opencapture\.localhost$ [NC]
    RewriteCond %{HTTPS} off
    RewriteRule ^(.*)$ https://%{HTTP_HOST}/edissyum/dist/ [R=301,L]

    #Header always set X-Content-Type-Options: nosniff
    #Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"

    <Directory /var/www/html/opencapture/>
    #    AllowOverride All
    #    WSGIProcessGroup opencapture
    #    WSGIApplicationGroup %{GLOBAL}
    #    WSGIPassAuthorization On
    #    Order deny,allow
    #    Allow from all
    #    Require all granted
        <Files ~ "(.ini|secret_key)">
            Require all denied
        </Files>
    </Directory>
</VirtualHost>

<VirtualHost *:443>
    ServerName opencapture.visiocompte.localhost
    ServerAlias apache_container
    DocumentRoot /var/www/html/opencapture/
    WSGIDaemonProcess opencapture user=opencapture group=www-data home=/var/www/html/opencapture/ threads=5 processes=1 python-path=/home/root/python-venv/opencapture/lib/python3.9/site-packages
    WSGIScriptAlias /backend_oc /var/www/html/opencapture//wsgi.py
    SSLEngine on
    SSLCertificateFile /etc/cert.pem
    SSLCertificateKeyFile /etc/key.pem
    SSLProtocol all -SSLv2 -SSLv3 -TLSv1 -TLSv1.1 
    <Directory /var/www/html/opencapture/>
        AllowOverride All
        WSGIProcessGroup opencapture
        WSGIApplicationGroup %{GLOBAL}
        WSGIPassAuthorization On
        Order deny,allow
        Allow from all
        Require all granted
        <Files ~ "(.ini|secret_key)">
            Require all denied
        </Files>
    </Directory>

</VirtualHost>